const SITE = {
  unit: "الوحدة 11 · الأمن السيبراني وإدارة الحوادث",
  grade: "الصف 12",
};

/** التسلسل التعليمي: أ3 ثم أ4 ثم أ5 */
const PATH = [
  { id: "vectors", group: "a3", label: "نواقل الهجوم", short: "نواقل الهجوم" },
  { id: "gdpr", group: "a3", label: "حماية البيانات", short: "حماية البيانات · GDPR" },
  { id: "misuse", group: "a3", label: "إساءة استخدام الحاسوب", short: "إساءة استخدام الحاسوب · Misuse" },
  { id: "comms", group: "a3", label: "تشريعات الاتصالات", short: "تشريعات الاتصالات" },
  { id: "fraud", group: "a3", label: "مكافحة الاحتيال", short: "مكافحة الاحتيال" },
  { id: "health", group: "a3", label: "الصحة والسلامة", short: "الصحة والسلامة" },
  { id: "site", group: "a4", label: "أمان الموقع", short: "أمان الموقع" },
  { id: "backup", group: "a4", label: "تخزين ونسخ احتياطي", short: "تخزين ونسخ احتياطي" },
  { id: "antivirus", group: "a5", label: "مكافحة الفيروسات", short: "مكافحة الفيروسات · Antivirus" },
  { id: "firewall", group: "a5", label: "جدران الحماية", short: "جدران الحماية · Firewall" },
  { id: "auth", group: "a5", label: "مصادقة المستخدم", short: "مصادقة المستخدم · Authentication" },
  { id: "access", group: "a5", label: "التحكم بالوصول والحوسبة الموثوقة", short: "التحكم بالوصول · Access" },
  { id: "encrypt", group: "a5", label: "التشفير", short: "التشفير · Encryption" },
  { id: "wlan", group: "a5", label: "حماية الشبكة اللاسلكية", short: "الشبكة اللاسلكية · WLAN" },
];

const A3 = PATH.filter((p) => p.group === "a3");
const A4 = PATH.filter((p) => p.group === "a4");
const A5 = PATH.filter((p) => p.group === "a5");

/**
 * مصطلحات الأمن السيبراني من المواصفات الإنجليزية.
 * say = النص الذي يُلفَظ عند الضغط على السماعة
 */
const GLOSSARY = [
  { en: "legal responsibilities", full: "Legal responsibilities", ar: "المسؤوليات القانونية", say: "legal responsibilities" },
  { en: "cyber security", full: "Cyber security", ar: "الأمن السيبراني", say: "cyber security" },
  { en: "data protection", full: "Data protection", ar: "حماية البيانات", say: "data protection" },
  { en: "GDPR", full: "General Data Protection Regulation", ar: "اللائحة العامة لحماية البيانات", say: "G D P R, General Data Protection Regulation" },
  { en: "Computer Misuse Act", full: "Computer Misuse Act", ar: "قانون إساءة استخدام الحاسوب", say: "Computer Misuse Act" },
  { en: "illegal practices", full: "Illegal practices", ar: "ممارسات غير قانونية", say: "illegal practices" },
  { en: "telecommunications legislation", full: "Telecommunications legislation", ar: "تشريعات الاتصالات", say: "telecommunications legislation" },
  { en: "monitor", full: "Monitor (communications)", ar: "مراقبة (الاتصالات)", say: "monitor" },
  { en: "fraud", full: "Fraud", ar: "الاحتيال", say: "fraud" },
  { en: "fraudulent purposes", full: "Fraudulent purposes", ar: "أغراض احتيالية", say: "fraudulent purposes" },
  { en: "health and safety", full: "Health and safety", ar: "الصحة والسلامة", say: "health and safety" },
  { en: "employers", full: "Employers", ar: "أصحاب العمل", say: "employers" },
  { en: "employees", full: "Employees", ar: "الموظفون", say: "employees" },
  { en: "attack vector", full: "Attack vector", ar: "ناقل الهجوم", say: "attack vector" },
  { en: "vulnerability", full: "Vulnerability", ar: "ثغرة أمنية", say: "vulnerability" },
  { en: "physical security measures", full: "Physical security measures", ar: "تدابير الأمان المادي", say: "physical security measures" },
  { en: "site security locks", full: "Site security locks", ar: "أقفال أمان الموقع", say: "site security locks" },
  { en: "card entry", full: "Card entry", ar: "الدخول بالبطاقة", say: "card entry" },
  { en: "biometrics", full: "Biometrics", ar: "القياسات الحيوية", say: "biometrics" },
  { en: "CCTV", full: "Closed-Circuit Television", ar: "دوائر تلفزيونية مغلقة — كاميرات مراقبة", say: "C C T V, closed-circuit television" },
  { en: "security staff", full: "Security staff", ar: "موظفو الأمن", say: "security staff" },
  { en: "alarms", full: "Alarms", ar: "أجهزة الإنذار", say: "alarms" },
  { en: "protected cabling", full: "Protected cabling", ar: "الكابلات المحمية", say: "protected cabling" },
  { en: "cabinets", full: "Cabinets", ar: "الخزائن", say: "cabinets" },
  { en: "data storage", full: "Data storage", ar: "تخزين البيانات", say: "data storage" },
  { en: "backup", full: "Backup", ar: "نسخ احتياطي", say: "backup" },
  { en: "automated backup", full: "Planned automated backup", ar: "نسخ احتياطي آلي مخطّط", say: "planned automated backup" },
  { en: "on-site", full: "On-site data storage", ar: "تخزين داخل الموقع", say: "on-site" },
  { en: "off-site", full: "Off-site data storage", ar: "تخزين خارج الموقع", say: "off-site" },
  { en: "cloud storage", full: "Cloud storage", ar: "التخزين السحابي", say: "cloud storage" },
  { en: "antivirus software", full: "Antivirus software", ar: "برامج مكافحة الفيروسات", say: "antivirus software" },
  { en: "virus signatures", full: "Virus signatures", ar: "توقيعات الفيروسات", say: "virus signatures" },
  { en: "heuristics", full: "Heuristics techniques", ar: "تقنيات الاستدلال / الموجِّهات", say: "heuristics" },
  { en: "quarantine", full: "Quarantine", ar: "العزل", say: "quarantine" },
  { en: "firewall", full: "Firewall", ar: "جدار الحماية", say: "firewall" },
  { en: "packet filtering", full: "Packet filtering and inspection", ar: "تصفية الحزم وفحصها", say: "packet filtering and inspection" },
  { en: "application layer awareness", full: "Application layer awareness", ar: "الوعي بطبقة التطبيقات", say: "application layer awareness" },
  { en: "inbound rules", full: "Inbound rules", ar: "قواعد واردة", say: "inbound rules" },
  { en: "outbound rules", full: "Outbound rules", ar: "قواعد صادرة", say: "outbound rules" },
  { en: "network address", full: "Network address", ar: "عنوان الشبكة", say: "network address" },
  { en: "NAT", full: "Network Address Translation", ar: "ترجمة عنوان الشبكة", say: "N A T, network address translation" },
  { en: "LAN", full: "Local Area Network", ar: "شبكة المنطقة المحلية", say: "L A N, local area network" },
  { en: "WAN", full: "Wide Area Network", ar: "شبكة واسعة النطاق", say: "W A N, wide area network" },
  { en: "IP", full: "Internet Protocol", ar: "عنوان بروتوكول الإنترنت", say: "I P, internet protocol" },
  { en: "packet", full: "Packet", ar: "حزمة بيانات", say: "packet" },
  { en: "port", full: "Port", ar: "منفذ شبكة", say: "port" },
  { en: "protocol", full: "Protocol", ar: "بروتوكول", say: "protocol" },
  { en: "user authentication", full: "User authentication", ar: "مصادقة المستخدم", say: "user authentication" },
  { en: "login", full: "User login procedures", ar: "إجراءات تسجيل الدخول", say: "login" },
  { en: "strong password", full: "Strong password", ar: "كلمة مرور قوية", say: "strong password" },
  { en: "graphical password", full: "Text and graphical password", ar: "كلمة مرور نصية ورسومية", say: "graphical password" },
  { en: "biometric authentication", full: "Biometric authentication", ar: "المصادقة البيومترية", say: "biometric authentication" },
  { en: "two-step verification", full: "Two-step verification", ar: "التحقق بخطوتين", say: "two-step verification" },
  { en: "2FA", full: "Two-Factor Authentication", ar: "المصادقة الثنائية", say: "two F A, two-factor authentication" },
  { en: "security tokens", full: "Security tokens", ar: "رموز الأمان", say: "security tokens" },
  { en: "USB", full: "Universal Serial Bus", ar: "منفذ/وسيط USB", say: "U S B" },
  { en: "NFC", full: "Near Field Communication", ar: "الاتصال قريب المدى", say: "N F C, near field communication" },
  { en: "knowledge-based authentication", full: "Knowledge-based authentication", ar: "المصادقة القائمة على المعرفة", say: "knowledge-based authentication" },
  { en: "Kerberos", full: "Kerberos network authentication", ar: "مصادقة شبكة كيربيروس", say: "Kerberos" },
  { en: "certificate-based authentication", full: "Certificate-based authentication", ar: "المصادقة المستندة إلى الشهادات", say: "certificate-based authentication" },
  { en: "Active Directory", full: "Active Directory (AD)", ar: "أكتيف ديرِكتوري", say: "Active Directory" },
  { en: "access controls", full: "Access controls", ar: "عناصر التحكم في الوصول", say: "access controls" },
  { en: "trusted computing", full: "Trusted computing", ar: "الحوسبة الموثوقة", say: "trusted computing" },
  { en: "TPM", full: "Trusted Platform Module", ar: "وحدة الأنظمة الأساسية الموثوقة", say: "T P M, trusted platform module" },
  { en: "encryption", full: "Encryption", ar: "التشفير", say: "encryption" },
  { en: "symmetric encryption", full: "Symmetric encryption", ar: "التشفير المتماثل — مفتاح واحد يشفّر ويفك", say: "symmetric encryption" },
  { en: "asymmetric encryption", full: "Asymmetric encryption", ar: "التشفير غير المتماثل — مفتاح عام ومفتاح خاص", say: "asymmetric encryption" },
  { en: "session key", full: "Session key", ar: "مفتاح الجلسة", say: "session key" },
  { en: "open source", full: "Open source", ar: "مصدر مفتوح — يمكن رؤية الشفرة وتعديلها", say: "open source" },
  { en: "tunneling protocol", full: "Tunneling protocol", ar: "البروتوكول النفقي", say: "tunneling protocol" },
  { en: "DRM", full: "Digital Rights Management", ar: "إدارة الحقوق الرقمية", say: "D R M, digital rights management" },
  { en: "disc encryption", full: "File, folder, disc encryption", ar: "تشفير الملفات والمجلدات والأقراص", say: "disc encryption" },
  { en: "BitLocker", full: "BitLocker", ar: "تشفير القرص في ويندوز", say: "BitLocker" },
  { en: "EFS", full: "Encrypting File System", ar: "نظام الملفات المشفرة", say: "E F S, encrypting file system" },
  { en: "communications encryption", full: "Communications encryption", ar: "تشفير الاتصالات", say: "communications encryption" },
  { en: "Tor", full: "The Onion Router (Tor)", ar: "جهاز التوجيه البصلي / تور", say: "Tor, the onion router" },
  { en: "VPN", full: "Virtual Private Network", ar: "شبكة افتراضية خاصة", say: "V P N, virtual private network" },
  { en: "digital certificate", full: "Digital certificate", ar: "شهادة رقمية", say: "digital certificate" },
  { en: "certificate authority", full: "Certificate Authority (CA)", ar: "هيئة/سلطة الشهادات", say: "certificate authority" },
  { en: "HTTPS", full: "Hypertext Transfer Protocol Secure", ar: "بروتوكول نقل النص التشعبي الآمن", say: "H T T P S, hypertext transfer protocol secure" },
  { en: "public key", full: "Public key", ar: "المفتاح العام", say: "public key" },
  { en: "private key", full: "Private key", ar: "المفتاح الخاص", say: "private key" },
  { en: "WLAN", full: "Wireless Local Area Network", ar: "شبكة محلية لاسلكية", say: "W L A N, wireless local area network" },
  { en: "Wi‑Fi", full: "Wi-Fi", ar: "شبكة لاسلكية", say: "Wi-Fi" },
  { en: "MAC address filtering", full: "MAC address filtering", ar: "تصفية عناوين MAC", say: "MAC address filtering" },
  { en: "MAC", full: "Media Access Control address", ar: "عنوان التحكم في الوصول إلى الوسائط", say: "M A C address" },
  { en: "SSID", full: "Service Set Identifier", ar: "معرف مجموعة الخدمة — اسم شبكة Wi‑Fi", say: "S S I D, service set identifier" },
  { en: "WEP", full: "Wired Equivalent Privacy", ar: "الخصوصية السلكية المكافئة — تشفير قديم ضعيف", say: "W E P, wired equivalent privacy" },
  { en: "WPA", full: "Wi-Fi Protected Access", ar: "الوصول المحمي عبر Wi‑Fi", say: "W P A, Wi-Fi protected access" },
  { en: "WPA2", full: "Wi-Fi Protected Access 2", ar: "الوصول المحمي عبر Wi‑Fi 2 — المعيار الموصى به", say: "W P A 2, Wi-Fi protected access 2" },
  { en: "WPS", full: "Wi-Fi Protected Setup", ar: "الإعداد المحمي بتقنية Wi‑Fi", say: "W P S, Wi-Fi protected setup" },
  { en: "AES", full: "Advanced Encryption Standard", ar: "نظام التشفير المتقدم", say: "A E S, advanced encryption standard" },
  { en: "brute-force attack", full: "Brute-force attack", ar: "هجوم القوة الغاشمة", say: "brute-force attack" },
  { en: "unauthorised access", full: "Unauthorised access", ar: "وصول غير مصرح به", say: "unauthorised access" },
  { en: "phishing", full: "Phishing", ar: "التصيّد", say: "phishing" },
  { en: "NTFS", full: "New Technology File System", ar: "نظام ملفات ويندوز", say: "N T F S" },
  { en: "KDC", full: "Key Distribution Center", ar: "مركز توزيع المفاتيح", say: "K D C, key distribution center" },
  { en: "PIN", full: "Personal Identification Number", ar: "رقم التعريف الشخصي", say: "P I N" },
  { en: "GSM", full: "Global System for Mobile communications", ar: "نظام الاتصالات المتنقلة العالمي", say: "G S M" },
  { en: "offline attack", full: "Offline attack", ar: "هجوم غير متصل بالإنترنت", say: "offline attack" },
];

const PAGE_VOCAB = {};
